import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import Card from '@/component/Card'
import Header from '@/component/Header'
import getAllCategories from '@/lib/getAllCategories'
import { getPostsOnFirstPage } from '@/lib/getSitemap'


export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header categories={props.categories} />
        <div className={styles['card-container']}>
          {props.posts.map((each) => {
            return (
              <Card
                title={each.title}
                thumbnail={each.thumbnailURL}
                url={"/post/" + each.postURL}
                postDate={each.postDate}
                key={each.title}
                mode="curator"
              />
            );
          })}
        </div>
      </main>
    </>
  )
}


export async function getStaticProps(context) {

  const categories = await getAllCategories();
  const { posts, canLoadMoreSitemap } = await getPostsOnFirstPage();
  return {
    props: {
      categories,
      posts,
      canLoadMoreSitemap
    }
  }
}